<template>
  <div class="box m-1 py-2 px-3 is-clickable" @mouseover="hover = true" @mouseleave="hover = false">
    <section class="is-flex is-justify-content-space-between">
      <div class="subject">
        <strong>{{ subject }}</strong>
      </div>

      <div class="icon-text is-flex is-align-items-center has-tooltip-right"
        :class="{'has-tooltip-danger': pollutions.level > 2, 'has-tooltip-warning': pollutions.level > 0, 'has-tooltip-success': pollutions.level == 0}"
        :data-tooltip="pollutions.level > 2 ?  'This thread has a high pollution':
                       pollutions.level > 0 ?  'This thread has a mild pollution': 
                                               'This thread has a low pollution'">
        <span class="mx-1">{{readableCo2}} of CO<sub>2</sub></span>
        <span class="icon is-medium ">
          <img :src="require(`../assets/speedometer${pollutions.level}.svg`)"
            alt="an image showing the intensity of the pollution generated">
        </span>
      </div>
    </section>

    <section v-show="hover && hasComparisons">
      <!-- This is equivalent to: a ameliorer + donner au max les 3 meilleurs comparaison au lieu de tous -->
      <p class="mb-2">The pollution generated by this conversation is the same as:</p>
      <div class="columns is-centered">
        <div class="column has-text-centered" v-for="(cmp, index) in pollutionsWithOr" :key="index">
          <p class="heading is-size-6" v-if="cmp==='or'">or</p>
          <div v-else>
            <div class="icon">
              <img :src="require(`../assets/${cmp.name}.svg`)"
                alt="an image showing the comparison of the pollution generated"
                :title="`This thread pollutes as much as ${cmp.msg}`">
            </div>
            <p class="heading">{{cmp.msg}}</p>
          </div>
        </div>
      </div>
    </section>

  </div>
</template>

<script>
import {
    getAllComparisons
} from "../utils/pollution";
const convert = require('convert-units')


export default {
  data(){
    return {
      hover: false,
    }
  },
  props: {
    subject: {
      type: String,
      required: true
    },
    co2: {
      type: Number,
      required: true
    },
  },
  computed: {
    readableCo2() {
      let co2 = convert(this.co2).from('g').toBest({ exclude: ['mcg', 'mg', 'oz', 'lb', 'mt'] })
      return `${co2.val.toFixed(2)}${co2.unit}`
    },
    pollutions(){
      let allComparisons = getAllComparisons(this.co2)
      allComparisons.comparisons = allComparisons.comparisons.slice(-3)
      return allComparisons
    },
    pollutionsWithOr(){
      return [].concat(...this.pollutions.comparisons.map(n => [n, 'or'])).slice(0, -1)
    },
    hasComparisons(){
      return this.pollutions.comparisons.length
    },
  },
}
</script>

<style scoped>
@import "./../../node_modules/@creativebulma/bulma-tooltip/dist/bulma-tooltip.min.css";
.subject{
  max-width: 80%;
}
.box {
  min-height: 10%;
  box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
}
.box:hover {
  background-color: rgb(247, 245, 245);
}

</style>