# Generated by Django 3.1.6 on 2021-02-19 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('seen', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('size', models.IntegerField()),
                ('received_at', models.DateTimeField()),
                ('message_id', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=255)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('email_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailheaders')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_unsubscribe', models.CharField(max_length=255)),
                ('one_click', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InReplyTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_reply_to', models.CharField(max_length=255)),
                ('email_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailheaders')),
            ],
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='unsubscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.newsletter'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('email_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailheaders')),
            ],
        ),
    ]
