# Generated by Django 3.1.6 on 2021-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='email',
            new_name='email_header',
        ),
        migrations.RenameField(
            model_name='inreplyto',
            old_name='email',
            new_name='email_header',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='email',
            new_name='email_header',
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
