# Generated by Django 3.1.6 on 2021-02-17 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20210214_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailheaders',
            old_name='sender',
            new_name='folder',
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='sender_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
