# Generated by Django 3.1.6 on 2021-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20210223_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='email_header',
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='thread_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='InReplyTo',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
