# Generated by Django 3.1.6 on 2021-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20210217_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailheaders',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailheaders',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
