# Generated by Django 3.1.6 on 2021-02-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20210217_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailheaders',
            name='unsubscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.newsletter'),
        ),
        migrations.AlterField(
            model_name='emailheaders',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
