# Generated by Django 3.1.6 on 2021-02-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20210226_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='email_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.emailheaders'),
        ),
    ]
