# Generated by Django 3.1.6 on 2021-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_auto_20210219_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sender_email',
            field=models.EmailField(default='e@z.c', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Unsubscribe',
        ),
    ]
