# Generated by Django 3.1.6 on 2021-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_auto_20210228_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailheaders',
            name='co2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
