# Generated by Django 3.1.6 on 2021-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_auto_20210314_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailheaders',
            name='received_email',
            field=models.BooleanField(default=False),
        ),
    ]
