# Generated by Django 3.1.6 on 2021-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_emailheaders_received_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailheaders',
            name='received_email',
            field=models.BooleanField(default=True),
        ),
    ]
