# Generated by Django 3.1.6 on 2021-03-16 14:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0015_auto_20210315_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailheaders',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmailStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_size', models.PositiveIntegerField()),
                ('emitted_co2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('email_count', models.PositiveIntegerField()),
                ('emails_seen_count', models.PositiveIntegerField()),
                ('emails_received_count', models.PositiveIntegerField()),
                ('saved_co2', models.PositiveIntegerField(default=0)),
                ('email_removed_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
