# Generated by Django 3.1.6 on 2021-03-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_auto_20210316_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailheaders',
            name='received',
        ),
    ]
