# Generated by Django 3.1.6 on 2021-03-20 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0022_auto_20210319_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstats',
            name='saved_co2',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
