# Generated by Django 3.1.6 on 2021-03-26 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0023_auto_20210320_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailheaders',
            name='carbon_yforecast',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
