# Generated by Django 3.1.6 on 2021-03-25 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0023_auto_20210320_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailstats',
            old_name='emitted_co2',
            new_name='current_emitted_co2',
        ),
        migrations.AddField(
            model_name='emailstats',
            name='emitted_co2_at_creation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
