# Generated by Django 3.1.6 on 2021-03-25 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0024_auto_20210325_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstats',
            name='current_emitted_co2',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='emitted_co2_at_creation',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
