# Generated by Django 3.1.6 on 2021-03-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0027_auto_20210325_1133'),
        ('emails', '0024_emailheaders_carbon_yforecast'),
    ]

    operations = [
    ]
