# Generated by Django 3.1.6 on 2021-04-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0028_merge_20210327_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailheaders',
            options={'ordering': ['-received_at']},
        ),
    ]
