# Generated by Django 3.1.6 on 2021-04-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0029_auto_20210401_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailheaders',
            options={},
        ),
    ]
