# Generated by Django 3.1.6 on 2021-04-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0030_auto_20210401_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailheaders',
            name='unsubscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_headers', to='emails.newsletter'),
        ),
    ]
