# Generated by Django 3.1.6 on 2021-04-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0031_auto_20210405_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailheaders',
            old_name='co2',
            new_name='generated_carbon',
        ),
    ]
