# Generated by Django 3.1.6 on 2021-04-07 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0032_auto_20210405_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='generated_carbon',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
