# Generated by Django 3.1.6 on 2021-04-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0035_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstats',
            name='badges_shared',
            field=models.BooleanField(default=False, help_text='The user has shared his badges on social media'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='connected_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the user connected to ErasMail'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='deleted_attachments_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted attachments'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='deleted_emails_larger2MB_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted emails larger than 2 MB'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='deleted_emails_older3Y_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted emails older than 3 years'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='deleted_emails_useless_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted useless emails'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='newsletters_deleted_emails_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of newsletters related emails deleted'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='newsletters_unsubscribed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of unsubscribed newsletters'),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='threads_deleted_emails_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of threads related emails deleted'),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='deleted_emails_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted emails'),
        ),
    ]
