# Generated by Django 3.1.6 on 2021-04-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0036_auto_20210421_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailstats',
            name='connected_count',
        ),
    ]
