# Generated by Django 3.1.6 on 2021-04-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0037_remove_emailstats_connected_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstats',
            name='stats_shared',
            field=models.PositiveIntegerField(default=0, help_text='The user has shared his stats on social media'),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='badges_shared',
            field=models.PositiveIntegerField(default=0, help_text='The user has shared his badges on social media'),
        ),
        migrations.DeleteModel(
            name='Success',
        ),
    ]
