# Generated by Django 3.1.6 on 2021-04-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0039_auto_20210422_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_emails_larger2MB_count',
            new_name='deleted_emails_largerF_count',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_emails_older3Y_count',
            new_name='deleted_emails_olderF_count',
        ),
    ]
