# Generated by Django 3.1.6 on 2021-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0040_auto_20210422_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstats',
            name='deleted_emails_largerF_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted emails using the larger than filter'),
        ),
        migrations.AlterField(
            model_name='emailstats',
            name='deleted_emails_olderF_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of deleted emails using the older than filter'),
        ),
    ]
