# Generated by Django 3.1.6 on 2021-04-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0041_auto_20210423_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailstats',
            old_name='newsletters_erasmail_unsubscribed_count',
            new_name='unsubscribed_newsletters_count',
        ),
    ]
