# Generated by Django 3.1.6 on 2021-04-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0042_auto_20210423_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_attachments_count',
            new_name='deleted_attachments',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_emails_largerF_count',
            new_name='deleted_emails_larger_filter',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='newsletters_deleted_emails_count',
            new_name='deleted_emails_newsletters_feature',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_emails_olderF_count',
            new_name='deleted_emails_older_filter',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='threads_deleted_emails_count',
            new_name='deleted_emails_threads_feature',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_emails_useless_count',
            new_name='deleted_emails_useless_filter',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='emails_received_count',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='emails_seen_count',
            new_name='received',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='badges_shared',
            new_name='shared_badges',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='stats_shared',
            new_name='shared_stats',
        ),
        migrations.RenameField(
            model_name='emailstats',
            old_name='unsubscribed_newsletters_count',
            new_name='unsubscribed_newsletters',
        ),
    ]
