# Generated by Django 3.1.6 on 2021-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0043_auto_20210425_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailheaders',
            name='receiver_email',
            field=models.EmailField(default='a', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailheaders',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
