# Generated by Django 3.1.6 on 2021-04-27 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0043_auto_20210426_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailstats',
            name='carbon_eq',
        ),
        migrations.RemoveField(
            model_name='emailstats',
            name='carbon_eq_at_creation',
        ),
        migrations.RemoveField(
            model_name='emailstats',
            name='mailbox_size',
        ),
        migrations.RemoveField(
            model_name='emailstats',
            name='months_since_creation',
        ),
        migrations.RemoveField(
            model_name='emailstats',
            name='saved_co2',
        ),
        migrations.AddField(
            model_name='emailstats',
            name='created_since_months',
            field=models.FloatField(default=0, help_text='Number of months since creation of email account, based on first stored received email', validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailstats',
            name='emailbox_carbon',
            field=models.FloatField(default=0, help_text='Emailbox current carbon equivalent', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='emailstats',
            name='emailbox_initial_carbon',
            field=models.FloatField(default=0, help_text='Carbon equivalent of the emailbox at the first connection ever', validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailstats',
            name='emailbox_size',
            field=models.PositiveIntegerField(default=0, help_text='Emailbox current size (bytes)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailstats',
            name='saved_carbon',
            field=models.FloatField(default=0, help_text='Total saved carbon by the current user', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
