# Generated by Django 3.1.6 on 2021-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0044_auto_20210425_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailheaders',
            name='receiver_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
