# Generated by Django 3.1.6 on 2021-04-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0044_auto_20210427_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailstats',
            old_name='deleted_emails_count',
            new_name='deleted_emails',
        ),
    ]
