# Generated by Django 3.1.6 on 2021-04-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0045_auto_20210425_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailheaders',
            name='is_received',
        ),
    ]
