# Generated by Django 3.1.6 on 2021-04-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0047_auto_20210425_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailheaders',
            name='receiver_email',
            field=models.EmailField(max_length=254),
        ),
    ]
