# Generated by Django 3.1.6 on 2021-04-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0048_auto_20210425_0814'),
        ('emails', '0045_auto_20210427_0131'),
    ]

    operations = [
    ]
