# Generated by Django 3.1.6 on 2021-02-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210207_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='app_password',
        ),
    ]
