# Generated by Django 3.1.6 on 2021-04-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210421_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='connected_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the user connected to ErasMail'),
        ),
    ]
