# Generated by Django 3.1.6 on 2021-04-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_success'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Success',
        ),
    ]
